package com.calvin.flink.example.model;

import lombok.Data;

import java.time.LocalDateTime;

@Data
public class WeworkCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   对应的企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.wework_corp_id
     *
     * @mbg.generated
     */
    private String weworkCorpId;

    /**
     * Database Column Remarks:
     *   企微-外部联系人的user_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.external_user_id
     *
     * @mbg.generated
     */
    private String externalUserId;

    /**
     * Database Column Remarks:
     *   企微-外部联系人的名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   企微-外部联系人的职位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     * Database Column Remarks:
     *   企微-外部联系人头像URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     * Database Column Remarks:
     *   企微-外部联系人所在企业的简称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.corp_name
     *
     * @mbg.generated
     */
    private String corpName;

    /**
     * Database Column Remarks:
     *   企微-外部联系人所在企业的主体名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.corp_full_name
     *
     * @mbg.generated
     */
    private String corpFullName;

    /**
     * Database Column Remarks:
     *   企微-外部联系人的类型，1表示该外部联系人是微信用户，2表示该外部联系人是企业微信用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   企微-外部联系人在微信开放平台的唯一身份标识（微信unionid）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.unionid
     *
     * @mbg.generated
     */
    private String unionid;

    /**
     * Database Column Remarks:
     *   企微-外部联系人性别 0-未知 1-男性 2-女性
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.gender
     *
     * @mbg.generated
     */
    private Integer gender;

    /**
     * Database Column Remarks:
     *   流失标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.lose
     *
     * @mbg.generated
     */
    private Boolean lose;

    /**
     * Database Column Remarks:
     *   首次添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.first_create_time
     *
     * @mbg.generated
     */
    private Long firstCreateTime;

    /**
     * Database Column Remarks:
     *   注册手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.register_phone
     *
     * @mbg.generated
     */
    private String registerPhone;

    /**
     * Database Column Remarks:
     *   此条数据创建的时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.create_at
     *
     * @mbg.generated
     */
    private LocalDateTime createAt;

    /**
     * Database Column Remarks:
     *   此条数据最后更新的时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.last_update_at
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdateAt;

    /**
     * Database Column Remarks:
     *   此条数据的创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   此条数据最后更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.last_update_by
     *
     * @mbg.generated
     */
    private Long lastUpdateBy;

    /**
     * Database Column Remarks:
     *   此条数据的版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.object_version
     *
     * @mbg.generated
     */
    private Long objectVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.content_length
     *
     * @mbg.generated
     */
    private Long contentLength;

    /**
     * Database Column Remarks:
     *   机器人开放平台客户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.rpa_contact_id
     *
     * @mbg.generated
     */
    private String rpaContactId;

    /**
     * Database Column Remarks:
     *   企微-外部联系人的user_id,密文
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wework_customer.encrypt_external_user_id
     *
     * @mbg.generated
     */
    private String encryptExternalUserId;
}
